### ISSUE TITLE
공원 상세 페이지 댓글창

### ISSUE THREAD

**Issue by nicesugi** [2JYK/iPark_django_backend#22]

**Comment by nicesugi** [comment]
댓글 조회는 공원 상세정보 열람시 확인이 되게 진행할 예정입니다
작성, 수정, 삭제 기능 구현했습니다.
수정, 삭제는 본인이 작성한 댓글만 가능하게 try, except 을 사용하였고 추가 조건을 부여했습니다.

**Comment by nicesugi** [comment]
공원 조회 url은 park/<park_id>/ 입니다.
현재 공원 상세 페이지에서의 댓글 작성시 url은  park/<park_id>/comment/ 입니다.
이 부분은 상세 페이지에서 볼 수 있는 공간이니 url이 같아야 하지않을까 싶습니다.

또한,
댓글의 수정,삭제시 url은  어떤게 좋을지 고민입니다.
1. park/<park_id>/ comment/<comment_id>/ 
2. park/ comment/<comment_id>/

**Comment by juhyun1011** [comment]
community 앱에서는 2번을 사용했습니다.

**Comment by nicesugi** [comment]
감사합니당. url 변경해서 push 했습니당 !!

댓글 작성 : park/<park_id>/comment/
댓글 수정,삭제 : park/<park_id>/comment/<comment_id>/
